apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
        labels: 
          app: event-bus
    spec:
      containers:
        - name: event-bus
          image: jacobmjjo/event-bus
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: event-bus-srv
spec:
  ports:
  - name: event-bus
    port: 4005
    protocol: TCP
    targetPort: 4005
  selector:
    app: event-bus
  type: ClusterIP
status:
  loadBalancer: {}

