apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
        labels: 
          app: comments
    spec:
      containers:
        - name: comments
          image: jacobmjjo/comments
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: comments-srv
spec:
  ports:
  - name: comments
    port: 4001
    protocol: TCP
    targetPort: 4001
  selector:
    app: comments
  type: ClusterIP
status:
  loadBalancer: {}
